#include <iostream>
#pragma once
void ShowGreetings();
void ShowTask();
void ShowOutputDataOption();
void ShowInputOption();
void ShowOutputType();
void ShowMassiveInput();
void ShowOutputChoice();
void ShowMassiveQuantity();